---
- name: "System | {{ ansible_distribution }} | Update pacman"
  community.general.pacman:
    update_cache: true
    upgrade: true
    state: latest
  become: true

- name: "System | {{ ansible_distribution }} | Install"
  community.general.pacman:
    name:
      - jq
      - unzip
      - autojump
      - btop
      - python3
      - kitty
      - ttf-font-awesome
      - ttf-nerd-fonts-symbols
    state: present
  become: true
