---
# tasks file for kitty

- name: Install kitty
  pacman:
    name: kitty
    state: present

- name: "Copy kitty config file"
  copy:
    src: "{{ role_path }}/files/kitty.conf"
    dest: "{{ ansible_user_dir }}/.config/kitty/kitty.conf"
    mode: "0644"

