---
- name: Check the OS distribution and install pipx
  block:
    - name: Gather facts about the target system
      setup:

    - name: Install pipx on Arch Linux
      pacman:
        name: python-pipx
        state: present
      become: true
      when: ansible_os_family == 'Archlinux'

    - name: Install pipx on Debian-based systems
      apt:
        name: python3-pipx
        state: present
      become: true
      when: ansible_os_family == 'Debian'
    # Ensure Python and pip are installed for both distributions
    - name: Install Python and pip and pexpect on Arch Linux
      pacman:
        name:
          - python
          - python-pip
          - python-pexpect
        state: present
      become: true
      when: ansible_os_family == 'Archlinux'

    - name: Install Python and pip on Debian-based systems
      apt:
        name:
          - python3
          - python3-pip
        state: present
      become: true
      when: ansible_os_family == 'Debian'

    - name: Install pexpect on Debian-based systems
      pip:
        name: pexpect
        executable: pip3
      become: true
      when: ansible_os_family == 'Debian'

- name: "Ensure the directory exists for home/petert/github"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/github"
    state: directory
    mode: '0755'

- name: "Clone Fabric repository"
  ansible.builtin.git:
    repo: 'https://github.com/danielmiessler/fabric.git'
    dest: "{{ ansible_user_dir }}/github/fabric"
    clone: yes
    update: yes

- name: "Install Fabric using pipx"
  ansible.builtin.command:
    cmd: "pipx install ."
  args:
    chdir: "{{ ansible_user_dir }}/github/fabric"

- name: "Ensure the directory exists for home/petert/.config/fabric"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/fabric"
    state: directory
    mode: '0755'

- name: "Decrypt values for.env file to the configuration directory"
  copy:
    dest: "{{ ansible_user_dir }}/.config/fabric/.env"
    content: "{{ fabric_config }}"
    owner: petert
    group: petert
    mode: "0644"
  no_log: true

- name: "Run Setup for fabric"
  ansible.builtin.expect:
    command: "fabric --setup"
    responses:
      (?i)Please enter your OpenAI API key.*: "\n"
      (?i)Please enter your claude API key.*: "\n"
      (?i)Please enter your YouTube API key.*: "\n"
    timeout: 30
