---
- name: "Neovim | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: neovim_distribution_config

- name: "Neovim | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: neovim_distribution_config.stat.exists

- name: "Clone neovim config file repo"
  ansible.builtin.git:
    repo: https://github.com/ptsiampas/kickstart.nvim.git
    dest: "{{ ansible_user_dir }}/.config/nvim"
    force: yes
    create_remote: yes
