---
- name: "Install unzip - to make sure we can unzip fonts"
  community.general.pacman:
    name:
      - unzip
    state: present
  become: true

# tasks file for Fonts
- name: Ensure .fonts directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.fonts"
    state: directory

- name: Download and unzip fonts
  block:
    - name: Download FiraCode font
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
        dest: "/tmp/FiraCode.zip"
        mode: '0444'

    - name: Unzip FiraCode font
      ansible.builtin.unarchive:
        src: "/tmp/FiraCode.zip"
        dest: "{{ ansible_user_dir }}/.fonts"
        remote_src: yes
        creates: "{{ ansible_user_dir }}/.fonts/FiraCode-Regular.ttf"  # Adjust based on actual file name
      notify: Update font cache

    - name: Download Meslo font
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Meslo.zip
        dest: "/tmp/Meslo.zip"
        mode: '0444'

    - name: Unzip Meslo font
      ansible.builtin.unarchive:
        src: "/tmp/Meslo.zip"
        dest: "{{ ansible_user_dir }}/.fonts"
        remote_src: yes
        creates: "{{ ansible_user_dir }}/.fonts/MesloLGM-Regular.ttf"  # Adjust based on actual file name
      notify: Update font cache
  become: no  # Assuming you're running this as the target user; adjust as needed

- name: Remove downloaded zip files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/FiraCode.zip"
    - "/tmp/Meslo.zip"

